controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\SignupForm;
use app\models\ContactForm;
use app\models\Shortstory;
use app\models\Article;
class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */

    public function beforeAction($action) {


        Yii::$app->view->theme = new \yii\base\Theme([
            'pathMap' => ['@app/views' => '@app/themes/front'],
            //'baseUrl' => '@web/themes/admin',
        ]);
        $this->layout = 'main';
        return parent::beforeAction($action);
    }
    
    // public function behaviors()
    // {
    //     return [
    //         'access' => [
    //             'class' => AccessControl::className(),
    //             'only' => ['logout'],
    //             'rules' => [
    //                 [
    //                     'actions' => ['logout'],
    //                     'allow' => true,
    //                     'roles' => ['@'],
    //                 ],
    //             ],
    //         ],
    //         'verbs' => [
    //             'class' => VerbFilter::className(),
    //             'actions' => [
    //                 'logout' => ['post'],
    //             ],
    //         ],
    //     ];
    // }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        $searchModel = new \app\models\ShortstorySearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams); 
        $dataProvider->query->andWhere(['published_status'=>'publish'])->orderBy(["ss_id"=>SORT_DESC]);
        //$dataProvider->pagination->pageSize=1;
        return $this->render('/site/index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        $addUser = new SignupForm();
        if ($addUser->load(Yii::$app->request->post())) {

            if ($user = $addUser->NewUser()) {
                if (Yii::$app->getUser()->login($user)) {
                    return $this->goHome();
                }
            }
        }


        $model->password = '';
        return $this->render('login', [
            'model' => $model, 'new' => $addUser
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    }

    public function actionTopics($name=null)
    {
        // Super Topic
        $searchModel = new \app\models\TopicSuperSearch();
        $dataProvider = $searchModel->search_front(Yii::$app->request->queryParams);
    //    $dataProvider->pagination->pageSize=40;
        $dataProvider->query->andWhere(['page_status'=>1]);

        // Topic
        $searchModel_1 = new \app\models\TopicSearch();
        $dataProvider_1 = $searchModel_1->search_front(Yii::$app->request->queryParams);
        $dataProvider_1->query->andWhere(['page_status'=>1]);
    //    $dataProvider_1->pagination->pageSize=40;


        return $this->render('topics', [
            'SuperModel' => $searchModel,
            'SuperProvider' => $dataProvider,
            'TopicModel' => $searchModel_1,
            'TopicProvider' =>  $dataProvider_1
        ]);
    }
    
    public function actionTopic($type, $id, $name)
    {   
        if($type == 's'){
            $model = \app\models\TopicSuper::find()->where(['super_topic_id' => $id])->one(); 
            $searchModel = new \app\models\ShortstorySearch();
            $dataProvider = $searchModel->search(Yii::$app->request->queryParams); 
            $dataProvider->query->andWhere(['main_topic' => $model->super_topic_id, 'published_status'=>'publish'])->orderBy(["ss_id"=>SORT_DESC]);
            // echo "<pre>";
            // print_r($dataProvider);
            // echo "</pre>";
           // die;
        }elseif($type == 't'){
            $model = \app\models\Topic::find()->where(['topic_id' => $id])->one();
            $searchModel = new \app\models\ShortstorySearch();
            $dataProvider = $searchModel->search(Yii::$app->request->queryParams); 
            $dataProvider->query->orWhere(['or','topic_1' => $model->topic_id, 'topic_2'=> $model->topic_id]);
            $dataProvider->query->andWhere(['published_status'=>'publish'])->orderBy(["ss_id"=>SORT_DESC]);
        }    
        return $this->render('topic_detail', [
            'model' => $model,
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,          
        ]);
    }

    public function actionSs($slug='', $id=0){
       
        $model='';
        if($id==0){
            $ss_main = Shortstory::find()->where('slug LIKE :slug',[':slug'=>$slug])->all();
            if(!empty($ss_main)){$id = $ss_main['0']['ss_id'];}
        }else{
            
            $ss_main = Shortstory::find()->where(['ss_id'=>$id])->all();
            if(!empty($ss_main)) {$slug = $ss_main['0']['slug'];}
         
        } 
        if(!empty($ss_main)){
            $model = $ss_main['0'];
        }
        return $this->render('ss', [
            'model'=> $model,
            'slug' => $slug,
            'id'=>$id
        ]);
    }
    /**
     * Displays Article Single page.
     * Accpect slug and Article id
     * @return string
     */
    public function actionArticle($slug='',$id=0){
        
        $model='';
        if($id==0){
            $article_main = Article::find()->with(['mainTopic','author'])->where('slug LIKE :slug',[':slug'=>$slug])->all();
            if(!empty($article_main)){$id = $article_main['0']['article_id'];}
        }else{
            
            $article_main = Article::find()->where(['article_id'=>$id])->all();
            if(!empty($article_main)) {$slug = $article_main['0']['article_id'];}
         
        } 
        if(!empty($article_main)){
            $model = $article_main['0'];
            $path =$model->content_path;
            if(file_exists($path))
            {$content = json_decode(file_get_contents($path));
            }
            else{
                $content=$path;
            }
        }
       
        $related_article = Article::find()->with(['mainTopic','author'])->where('main_topic	 LIKE :main_topic',[':main_topic'=>$model->main_topic])->all();
       
        return $this->render('article', [
            'content'=>$content,
            'model'=> $model,
            'slug' => $slug,
            'id'=>$id,
            'related_article'=>$related_article,
        ]);
        
    }

    
}

views/site/_home_ss.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\helpers\Url;
use yii\helpers\ArrayHelper;
use app\models\SsContent;
?>
<?php //pr($model->topic->name);die;?>
<!-- first client-testimonials -->
	
	<?php
// 		echo "<pre>";
// 		print_r($model);
// 		echo "</pre>";
//      die;
	?>
	<div class="client-testimonials">
        <div class="owl-carousel tesimonail">
	        <?php
	        	$slide = SsContent::find()->where(['ss_id'=>$model->ss_id])->all();
	        	
	        	$slide_count = count($slide);
	        	
	        	for($i = 0; $i < $slide_count; $i++){
	 
	        ?>	
          <div class="item">
          		<?php
          			if(isset($slide[$i]->Img_path)){
          		?>
               <div class="testimonail-profile scale-zoom-box">
                  <figure><img src="<?= Url::to(['/media/ss/'.$slide[$i]->ss_id.'/'.$slide[$i]->Img_path]); ?>" alt="img"></figure>
                  <?php
                  	if($i == 0){
                  ?>
                  <div class="banner-text"><p><a href="<?= Url::to(['site/ss?slug='.$model->slug]); ?>"><?= $model->title ?></a></p></div>
                  <?php
                  	}
                  ?>
              </div>
              
              <div class="client-des">
                <h4><?php echo date("d-M", strtotime($model->published_date)); ?></h4>
                <?= $slide[$i]->content ?>
                <span><a href="#">View Article</a></span>
              </div>
              <?php
                }else{
              ?>
              <div class="client-des same">
                 <h4><?= $model->title;?></h4>
                 <h5><?php echo date("d-M", strtotime($model->published_date)); ?></h5>
                
                <?= $slide[$i]->content ?>
                <span><a href="#">View Article</a></span>
              </div>
              <?php    
                }
              ?>            
          </div>
	        <?php
	        	}
	        ?>
        </div>
        <div class="social-icon"> 
          <div class="like-icon"><a href="#"><img src="<?php echo Url::to(['/themes/front/images/like.png'])?>" alt="like"></a></div>
          <ul>
            <li><a href="#"><img src="<?php echo Url::to(['/themes/front/images/facebook.png'])?>" alt="facebook"></a></li>
            <li><a href="#"><img src="<?php echo Url::to(['/themes/front/images/twitter.png'])?>" alt="twitter"></a></li>
            <li><a href="#"><img src="<?php echo Url::to(['/themes/front/images/instagram.png'])?>" alt="instagram"></a></li>
            <li><a href="#"><img src="<?php echo Url::to(['/themes/front/images/google-plus.png'])?>" alt="google-plus"></a></li>
          <li><a href="#"><img src="<?php echo Url::to(['/themes/front/images/three-dots.png'])?>" alt="three-dots" width="3"></a></li>
          </ul>
          <div class="bookmark-icon"><a href="#"><img src="<?php echo Url::to(['/themes/front/images/bookmark.png'])?>" alt="bookmark"></a></div>
        </div>
      </div>

views/site/_topics_ss.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\helpers\Url;
use yii\helpers\ArrayHelper;

	if(isset($model->super_topic_id) && !isset($model->topic_id)){
		$topic_id = $model->super_topic_id;
		$type = 's';
	}elseif(isset($model->topic_id)){
		$topic_id = $model->topic_id;
		$type = 't';
	}

?>

  <div class="col-sm-3">
	<div class="topic-box">
	<a href="<?=Url::to(['/site/topic', 'type'=> $type, 'id' => $topic_id, 'name' => $model->topic_name]);?>">
	<?php if(!empty($model->logo_path)){ ?>
	  <figure><img width="240" height="180" src="<?=Url::to(['/media/topic/'.$type.'/'.$topic_id.'/'.$model->logo_path]);?>" alt="<?= $model->topic_name ?>"></figure>
	<?php } else { ?>
		<figure><img width="240" height="180" src="<?=Url::to(['/media/topic/no.jpg']);?>" alt=""></figure>
	<?php } ?>	
	</a>
	  <h4><?=$model->topic_name;?></h4>
	  <?php 
	  /* if(!empty(Yii::$app->user->id)){
		 $follow =  \app\models\UserTopics::find()->where(['user_id' => Yii::$app->user->id, 'topic_id' => $model->id])->one();
		  
			if(empty($follow)){
		*/
		?>
	  <a href="<?=Url::to(['/site/add-follow','id' => $model->super_topic_id]);?>" title="Click Here To Follow">
		<button class="topic-id" rel="<?=$model->super_topic_id; ?>" type="submit">
			<img src="<?=Url::to(['/themes/front/images/follow-icon.png']);?>" alt="follow-icon">
			Follow
		</button>
		</a>
	  <?php
	  /* } else { 
		*/
	  ?>
	  <!-- <a href="<?=Url::to(['/site/remove-follow','id' => $model->super_topic_id]);?>" title="Click Here To Remove Follow">
		<button class="topic-id" rel="<?=$model->super_topic_id; ?>" type="submit">
			<img src="<?=Url::to(['/themes/front/images/follow-icon.png']);?>" alt="follow-icon">
			Following
		</button>
		</a> -->
	  <?php 
		/*	}
	  } else { */

	  ?>
	  <!-- <a href="javascript:void(0);" title="Need To Login First">
		<button class="topic-id" rel="<?=$model->super_topic_id; ?>" type="submit">
			<img src="<?=Url::to(['/themes/front/images/follow-icon.png']);?>" alt="follow-icon">
			Follow
		</button>
		</a> -->
	  <?php // } ?>
	</div>
  </div>
    

views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        This is the About page. You may modify the following file to customize its content:
    </p>

    <code><?= __FILE__ ?></code>
</div>

views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else:

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
use yii\bootstrap\ActiveForm;
use yii\bootstrap\Modal;
use yii\helpers\ArrayHelper;
use yii\widgets\ListView;
$this->title = Yii::t('app', 'Home');
?>
<style>
.help-block-error{
    color:red;
}
.main-section {
    font-size: 15px;
}
.ias-trigger a {
    background-color: #593466;
    color: #fff;
    padding:10px;
}
</style>
<div id="overlay" onclick="off()"></div>
<!-- MAIN SECTION START -->
<div class="main-section">
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-3">
        <?= \app\components\TopicWidget::widget(); ?>
      </div>
      <div class="col-sm-6">
        <div class="meddle-section">
          <?= ListView::widget([
                'dataProvider' => $dataProvider,
                'itemView' => '_home_ss',
                //'itemOptions' => ['class' => 'item'],
                //'pager' => ['class' => \kop\y2sp\ScrollPager::className()]
            ]); ?>
        </div>
      </div>
   
      <div class="col-sm-3">
          <div class="right-section-wrapper">
            <?=  \app\components\TrendingWidget::widget(); ?>
          </div>
      </div>
    </div>
  </div>
</div>

views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

        <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

        <?= $form->field($model, 'password')->passwordInput() ?>

        <?= $form->field($model, 'rememberMe')->checkbox([
            'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
        ]) ?>

        <div class="form-group">
            <div class="col-lg-offset-1 col-lg-11">
                <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>
        </div>

    <?php ActiveForm::end(); ?>

    <div class="col-lg-offset-1" style="color:#999;">
        You may login with <strong>admin/admin</strong> or <strong>demo/demo</strong>.<br>
        To modify the username/password, please check out the code <code>app\models\User::$users</code>.
    </div>
</div>


<h2>Sign up</h2>
<?php $form = ActiveForm::begin([
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

        <?= $form->field($new, 'username')->textInput(['autofocus' => true]) ?>

        <?= $form->field($new, 'email')->textInput(['autofocus' => true]) ?>

        <?= $form->field($new, 'password')->passwordInput() ?>

        <div class="form-group">
            <div class="col-lg-offset-1 col-lg-11">
                <?= Html::submitButton('Sign Up', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>
        </div>

    <?php ActiveForm::end(); ?>

views/site/ss.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\helpers\Url;
use yii\helpers\ArrayHelper;
use app\models\SsContent;


$this->title = Yii::t('app', $slug);
?>
<style>
.main-section {
    font-size: 15px;
}
.ias-trigger a {
    background-color: #593466;
    color: #fff;
	padding:10px;
}
</style>
<!-- MAIN SECTION START -->

<div class="main-section technology All-topic">
    <div class="container">
    <hr>
    <?= \app\components\TopicWidget::widget(); ?>
    <?php if(!empty($model)){?>
        <div class="meddle-section">
            <div class="row">
                <div class="col-md-12">
                    <h3 style="text-transform: capitalize;"><?= $model?$model->title:'' ?></h3>
                </div>
            </div>
            <hr>
            <div class="row">
                <div class=" client-testimonials">
                    <div class="owl-carousel tesimonail">
                        <?php
                        $slide = SsContent::find()->where(['ss_id'=>$id])->all();
                        $slide_count = count($slide);
                        for($i = 0; $i < $slide_count; $i++){
                        ?>	
                        <div class="item">
                            <?php
                            if(isset($slide[$i]->Img_path)){
                            ?>
                        <div class="testimonail-profile">
                            <figure><img src="<?= Url::to(['/media/ss/'.$slide[$i]->ss_id.'/'.$slide[$i]->Img_path]); ?>" alt="img"></figure>
                            <?php
                            if($i == 0){
                            ?>
                        <div class="banner-text"><p><?= $model->title ?></p></div>
                            <?php
                            }
                            ?>
                        </div>
                        <div class="client-des">
                            <h4><?php echo date("d-M", strtotime($model->published_date)); ?></h4>
                            <?= $slide[$i]->content ?>
                            <span><a href="#">View Article</a></span>
                        </div>
                            <?php
                            }else{
                            ?>
                        <div class="client-des same">
                            <h4><?= $model->title;?></h4>
                            <h5><?php echo date("d-M", strtotime($model->published_date)); ?></h5>
                            <?= $slide[$i]->content ?>
                            <span><a href="#">View Article</a></span>
                        </div>
                            <?php    
                            }
                            ?>            
                    </div>
                    <?php
                        }
                    ?>
                </div>
                <div class="social-icon"> 
                    <div class="like-icon"><a href="#"><img src="<?php echo Url::to(['/themes/front/images/like.png'])?>" alt="like"></a></div>
                        <ul>
                            <li><a href="#"><img src="<?php echo Url::to(['/themes/front/images/facebook.png'])?>" alt="facebook"></a></li>
                            <li><a href="#"><img src="<?php echo Url::to(['/themes/front/images/twitter.png'])?>" alt="twitter"></a></li>
                            <li><a href="#"><img src="<?php echo Url::to(['/themes/front/images/instagram.png'])?>" alt="instagram"></a></li>
                            <li><a href="#"><img src="<?php echo Url::to(['/themes/front/images/google-plus.png'])?>" alt="google-plus"></a></li>
                            <li><a href="#"><img src="<?php echo Url::to(['/themes/front/images/three-dots.png'])?>" alt="three-dots" width="3"></a></li>
                        </ul>
                    <div class="bookmark-icon"><a href="#"><img src="<?php echo Url::to(['/themes/front/images/bookmark.png'])?>" alt="bookmark"></a></div>
                    </div>
                </div>
            </div>
        </div>
    <?php }else{?>
        <div class="meddle-section">
        <div class="row">
                <div class="col-md-12">
                    <h3 style="text-transform: capitalize;"><?= $model?$model->title:'Unable to find your search short story' ?></h3>
                </div>
            </div>
            <hr>
        </div>   
    <?php }?>
</div>

<!-- owlCarousel js -->
<script>
    $('.tesimonail').owlCarousel({
    loop:true,
    margin:10,
    nav:true,
    responsive:{
        0:{
            items:1
        }
    }
})
</script>

<script>
$('.tesimonail-related-post').owlCarousel({
    loop:true,
    margin:20,
    nav:true,
    responsive:{
        0:{
            items:1
        },
        480:{
            items:2
        },
        767:{
            items:4
        },
        1000:{
            items:5
        }
    }
})
</script>

views/site/topic_detail.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
use yii\bootstrap\ActiveForm;
use yii\bootstrap\Modal;
use yii\widgets\ListView;
use yii\helpers\ArrayHelper;

$this->title = Yii::t('app', $model->topic_name);
?>
<style>
.technology{
	font-size:15px;
}
</style>
<!-- MAIN SECTION START -->
<?php
	if(isset($model->super_topic_id) && !isset($model->topic_id)){
		$topic_id = $model->super_topic_id;
		$type = 's';
	}elseif(isset($model->topic_id)){
		$topic_id = $model->topic_id;
		$type = 't';
	}
?>

<div class="main-section technology">
  <div class="banner-section"><!-- banner section start-->

    <figure style="background-image:url(<?=Url::to(['/media/topic/'.$type.'/'.$topic_id.'/'.$model->cover_img_path]);?>); background-repeat: no-repeat; background-size: cover;"><img width = "1920" height = "402" style="background-color: black; opacity: <?= $model->transparent_score/100;?>"></figure>
      <div class="container">
      <div class="text-box">
        <p>138,648 Followers </p>
        <h1><?= $model->topic_name;?></h1>
        <p><?= $model->tag_line; ?></p>
        <div class="btn-div">
          <button type="submit">follow</button>
          <button type="submit">Add to home</button>
          <button type="submit">
            <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" x="0px" y="0px" viewBox="0 0 60 60" style="enable-background:new 0 0 60 60;" xml:space="preserve">
              <path d="M30,16c4.411,0,8-3.589,8-8s-3.589-8-8-8s-8,3.589-8,8S25.589,16,30,16z"/>
              <path d="M30,44c-4.411,0-8,3.589-8,8s3.589,8,8,8s8-3.589,8-8S34.411,44,30,44z"/>
              <path d="M30,22c-4.411,0-8,3.589-8,8s3.589,8,8,8s8-3.589,8-8S34.411,22,30,22z"/>
            </svg>
          </button>
        </div>
      </div>  
    </div>
  </div><!-- banner section end-->
  <div class="container">
    <?= \app\components\TopicWidget::widget(); ?>
    <div class="meddle-section">
			<?= ListView::widget([
            'dataProvider' => $dataProvider,
            'itemView' => '_home_ss',
            //'itemOptions' => ['class' => 'item'],
            //'pager' => ['class' => \kop\y2sp\ScrollPager::className()]
        ]); ?>
	 	</div>
	  <div class="right-section">
	    <?php // \app\components\TrandingWidget::widget(); 
	    ?>
		<div class="topscroll-btn">
	        <a href="#"><img src="<?=Url::to(['/themes/front/images/topscroll-btn.png']);?>" alt="img"></a>
	      </div>
	  </div>
  </div>
</div>
<?php // echo \app\components\ReportAbuseWidget::widget(); ?>