modules/admin/controllers/SsController.php
<?php

namespace app\modules\admin\controllers;

use Yii;
use app\models\Shortstory;
use app\models\ShortstorySearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\helpers\Json;
use app\models\Topic;
use app\models\TopicMedia;
use yii\helpers\ArrayHelper;
use yii\helpers\FileHelper;
use app\models\SsTags;
use app\models\SsContent;
/**
 * SsController implements the CRUD actions for Shortstory model.
 */
class SsController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Shortstory models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ShortstorySearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Shortstory model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Shortstory model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $this->layout = 'editor';
        $model = new Shortstory();

        
        
        if ($model->load(Yii::$app->request->post()) ) {          
            
            if($model->save()){

              $model =  $this->findModel($model->ss_id);
              $flag = 1; // Can Publish SS => Publish_Status = 'publish'
              
              $dir_path = Yii::getAlias('@webroot') .'/media/ss/'. $model->ss_id;

              if(! is_dir($dir_path)){
                  if(!FileHelper::createDirectory($dir_path, 0775))
                    throw new LocationException($dir_path . ' is not write');
              }


              //Content 

              $post_array = array_filter($_POST, function ($key) {
                return strpos($key, 'y_') === 0;
              }, ARRAY_FILTER_USE_KEY);
              
              $post_key = array_keys($post_array);
              $post_len = sizeof($post_key);
              
              if($post_len < 0){
                $post_content_ip = intval(str_replace('y_', '', $post_key[$post_len-1]));
              }else{
                $post_content_ip = 0;
              }

              $file_array = array_filter($_FILES, function ($key) {
                    return strpos($key, 'x_') === 0;
                  }, ARRAY_FILTER_USE_KEY);
                  
              $file_key = array_keys($file_array);
              $file_len = sizeof($file_key);
              
              if($file_len < 0){
                $file_content_ip = intval(str_replace('x_', '', $file_key[$file_len-1]));
              }else{
                $file_content_ip = 0;
              }

              $len = 0;
              if($file_content_ip >= $post_content_ip){
                $len = $file_content_ip;
              }else{
                $len = $post_content_ip;
              }
              // Content writter in db
              for($i = 0; $i<=$len; $i++){
                if(isset($_POST['y_'.$i]) || isset($_FILES['x_'.$i])){
                  $ss_slide_content = new SsContent();

                  if(isset($_POST['y_'.$i]) && isset($_FILES['x_'.$i])){
                      $temp_field = 'x_'.$i;
                      // Valid Image
                      $error_type = basename($_FILES[$temp_field]["error"]);
                      if($error_type == 0){
                        $LogoImg = $this->validateContentImg($temp_field, $dir_path , 600, 400);
                        $LogoImg = json_decode($LogoImg);
                        if(isset($LogoImg->success) ){
                            $ss_slide_content->Img_path =  $LogoImg->success;
                        }else{
                            // Error - Image is not uploaded into server

                        }
                      }else{
                        // Page Status - Active then It matters or Updating old logo
                        // Images alredy in database then no need to change page status
                                  
                      } 

                      $ss_slide_content->content = $_POST['y_'.$i];


                  }elseif(isset($_POST['y_'.$i])){
                    // Only Content
                    $ss_slide_content->content = $_POST['y_'.$i];

                  }elseif ( isset($_FILES['x_'.$i])) {
                    // Only Image
                    $temp_field = 'x_'.$i;
                      // Valid Image
                    $error_type = basename($_FILES[$temp_field]["error"]);
                    if($error_type == 0){
                      $LogoImg = $this->validateContentImg($temp_field, $dir_path , 600, 600);
                      $LogoImg = json_decode($LogoImg);
                      if(isset($LogoImg->success) ){
                          $ss_slide_content->Img_path =  $LogoImg->success;
                      }else{
                          // Error - Image is not uploaded into server

                      }
                    }else{
                      // Page Status - Active then It matters or Updating old logo
                      // Images alredy in database then no need to change page status
                                
                    } 
                  }
                  $ss_slide_content->ss_id = $model->ss_id;
                  $ss_slide_content->save();
                }
              }
              

              // Media Thumb and Cover Image
              // Media Thumb
              $error_type = basename($_FILES["Shortstory"]["error"]['media_thumb']);
              if($error_type == 0){
                $LogoImg = $this->validateImg('media_thumb', $dir_path , 220, 180);
                $LogoImg = json_decode($LogoImg);
                if(isset($LogoImg->success) ){
                    $model->media_thumb =  $LogoImg->success;
                }else{
                    // Error - Image is not uploaded into server
                  $flag = 0; // Unpubslish

                }
              }else{
                // Page Status - Active then It matters or Updating old logo
                // Images alredy in database then no need to change page status
                if(is_null($model->media_thumb)){
                    $flag = 0;
                }                    
              }                    

              // Cover Image
              // Give complete url in db either selected from topic default images or uploaded by user
              // First prefrence user uploaded images then default image
              $flag_cover = 1;
              $error_type = basename($_FILES["Shortstory"]["error"]['media_cover']);
              if($error_type == 0){
                $LogoImg = $this->validateImg('media_cover', $dir_path , 1600, 400);
                $LogoImg = json_decode($LogoImg);
                if(isset($LogoImg->success) ){
                    $model->media_cover =  '/media/ss/'. $model->ss_id.'/'.$LogoImg->success;
                }else{
                    // Error - Image is not uploaded into server
                  $flag = 0; // Unpubslish
                  $flag_cover = 0;

                }
              }else{
                // Check User selected Image from default topic option
                
                if(is_null($model->media_cover)){
                    $flag = 0;
                }
                $flag_cover = 0;                    
              }  
              // Now checking whether user selected default cover image
              if($flag_cover == 0){
                if(isset($_POST["coverImage"])){
                  if($_POST["coverImage"] != 0){
                      $path = TopicMedia::findOne($_POST["coverImage"]);
                  
                      $model->media_cover = '/media/topic/t/'.$path->topic_id.'/'.$path->media_path;
                      $flag_cover  = 1;
                  }
                }
              }

              //Sub Topic

              $tempcount = $_POST['Shortstory']['subTopic'];
              if($tempcount != null){
                if(count($tempcount) == 1){

                    $model->topic_1 =$_POST['Shortstory']['subTopic'][0]; 
                }elseif(count($tempcount) == 2){
                    $model->topic_1 = $_POST['Shortstory']['subTopic'][0];
                    $model->topic_2 = $_POST['Shortstory']['subTopic'][1];
                }
              }
              

              //Tags
              $tempcount =  $_POST['Shortstory']['tags'];
              if($tempcount != null){
                for($i = 0; $i < count($tempcount); $i++){
                  $SSTags = new SsTags();    
                  $SSTags->ss_id = $model->ss_id;
                  $SSTags->tag_name = $_POST['Shortstory']['tags'][$i];
                  $SSTags->save();
                }  
              }
              


              //if($flag == 0 || $flag_cover == 0){
              if($flag == 0){
                if($model->published_status == 'publish'){
                  
                      // Update session alert

modules/admin/views/layouts/editor.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\widgets\Alert;
use yii\helpers\Html;
use yii\widgets\Breadcrumbs;
use  yii\widgets\Menu;
use yii\helpers\Url;
use app\modules\admin\assets\EditorAsset;

EditorAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body class="skin-blue sidebar-mini">

<?php $this->beginBody() ?>

<div class="wrapper">

<header class="main-header">
    <!-- Logo -->
    <a href="<?=  Yii::$app->homeUrl ?>" class="logo">
      <!-- mini logo for sidebar mini 50x50 pixels -->
    <span class="logo-mini"><b>A</b>LT</span>
    <!-- logo for regular state and mobile devices -->
    <span class="logo-lg"><b>Admin</b>LTE</span>
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
      <!-- Sidebar toggle button-->
      <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
        <span class="sr-only">Toggle navigation</span>
      </a>

      <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">
          <!-- User Account: style can be found in dropdown.less -->
          <li class="dropdown user user-menu">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <img src="img/user2-160x160.jpg" class="user-image" alt="User Image">
              <span class="hidden-xs">Alexander Pierce</span>
            </a>
            <ul class="dropdown-menu">
              <!-- User image -->
              <li class="user-header">
                <img src="img/user2-160x160.jpg" class="img-circle" alt="User Image">

                <p>
                  Alexander Pierce - Web Developer
                  <small>Member since Nov. 2012</small>
                </p>
              </li>
              <!-- Menu Footer-->
              <li class="user-footer">
                <div class="pull-left">
                  <a href="#" class="btn btn-default btn-flat">Profile</a>
                </div>
                <div class="pull-right">
                  <a href="<?= Url::to(['site/logout'])?>" data-method="post" class="btn btn-default btn-flat">Sign out</a>
                </div>
              </li>
               <!-- Control Sidebar Toggle Button -->
            </ul>
          </li>
        </ul>
      </div>
    </nav>
</header>
<!-- Left side column. contains the logo and sidebar -->
<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">

      <?php
      echo Menu::widget([
                  'options' => ['tag' => 'ul class="sidebar-menu" data-widget="tree"'],
                  'submenuTemplate' => "\n<ul class='treeview-menu'>\n{items}\n</ul>\n",
                  'items' => [
                      ['label' => 'MAIN NAVIGATION', 'options' => ['class' => 'header']],
                      
                      ['label' => 'Dashboard', 'url' => ['site/index'], 'template' => '<a href="{url}"><i class="fa fa-dashboard"></i> <span>{label}</span></a>'],

                      ['label' => 'Article', 'url' => '#', 'options'=> ['class'=>'treeview'], 'template' => '<a href="{url}"><i class="fa fa-files-o"></i><span>{label}</span><span class="pull-right-container"><i class="fa fa-angle-left pull-right"></i></span></a>', 'items' => [
                          ['label' => 'Article List', 'url' => ['article/index'], 'template' => '<li><a href="{url}"><i class="fa fa-circle-o"></i>{label}</a></li>'],
                          ['label' => 'Approve Request', 'url' => '#', 'template' => '<li><a href="{url}"><i class="fa fa-circle-o"></i>{label}</a></li>'],
                      ]],

                      ['label' => 'Short Story', 'url' => '#', 'options'=> ['class'=>'treeview'], 'template' => '<a href="{url}"><i class="fa fa-files-o"></i><span>{label}</span><span class="pull-right-container"><i class="fa fa-angle-left pull-right"></i></span></a>', 'items' => [
                          ['label' => 'List SS', 'url' => ['ss/index'], 'template' => '<li><a href="{url}"><i class="fa fa-circle-o"></i>{label}</a></li>'],
                          ['label' => 'Approve Request', 'url' => '#', 'template' => '<li><a href="{url}"><i class="fa fa-circle-o"></i>{label}</a></li>'],
                      ]],

                      ['label' => 'Topics', 'url' => '#', 'options'=> ['class'=>'treeview'], 'template' => '<a href="{url}"><i class="fa fa-files-o"></i><span>{label}</span><span class="pull-right-container"><i class="fa fa-angle-left pull-right"></i></span></a>', 'items' => [
                          ['label' => 'Topic List', 'url' => ['topic/index'], 'template' => '<li><a href="{url}"><i class="fa fa-circle-o"></i>{label}</a></li>'],
                          ['label' => 'Super Topics', 'url' => ['super-topic/index'], 'template' => '<li><a href="{url}"><i class="fa fa-circle-o"></i>{label}</a></li>'],
                          ['label' => 'Default Home and Nav. Topics', 'url' => '#', 'template' => '<li><a href="{url}"><i class="fa fa-circle-o"></i>{label}</a></li>'],
                      ]],

                      ['label' => 'User', 'url' => '#', 'options'=> ['class'=>'treeview'], 'template' => '<a href="{url}"><i class="fa fa-files-o"></i><span>{label}</span><span class="pull-right-container"><i class="fa fa-angle-left pull-right"></i></span></a>', 'items' => [
                          ['label' => 'Manage User', 'url' => ['panel/index'], 'template' => '<li><a href="{url}"><i class="fa fa-circle-o"></i>{label}</a></li>'],
                      ]],
                  ],
              ]);


      ?>
    </section>
    <!-- /.sidebar -->
</aside>


<div class="content-wrapper">

    <section class="content-header">
      <h1>
        List of Articles
        <small>Manage Articles</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="#">Tables</a></li>
        <li class="active">Data tables</li>
      </ol>
    </section>

    <section class="content">
        <?= Alert::widget() ?>
        <?= $content ?>
    </section>
</div>
</div>
<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

modules/admin/views/layouts/login.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\widgets\Alert;
use yii\helpers\Html;
use yii\widgets\Breadcrumbs;
use  yii\widgets\Menu;
use yii\helpers\Url;
use app\modules\admin\assets\LoginAsset;

LoginAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body class="hold-transition login-page">

<?php $this->beginBody() ?>

        <?= Alert::widget() ?>
        <?= $content ?>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

modules/admin/views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\widgets\Alert;
use yii\helpers\Html;
use yii\widgets\Breadcrumbs;
use  yii\widgets\Menu;
use yii\helpers\Url;
use app\modules\admin\assets\AdminAsset;

AdminAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body class="skin-blue sidebar-mini">

<?php $this->beginBody() ?>

<div class="wrapper">

<header class="main-header">
    <!-- Logo -->
    <a href="<?=  Yii::$app->homeUrl ?>" class="logo">
      <!-- mini logo for sidebar mini 50x50 pixels -->
    <span class="logo-mini"><b>A</b>LT</span>
    <!-- logo for regular state and mobile devices -->
    <span class="logo-lg"><b>Admin</b>LTE</span>
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
      <!-- Sidebar toggle button-->
      <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
        <span class="sr-only">Toggle navigation</span>
      </a>

      <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">
          <!-- User Account: style can be found in dropdown.less -->
          <li class="dropdown user user-menu">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <img src="img/user2-160x160.jpg" class="user-image" alt="User Image">
              <span class="hidden-xs">Alexander Pierce</span>
            </a>
            <ul class="dropdown-menu">
              <!-- User image -->
              <li class="user-header">
                <img src="img/user2-160x160.jpg" class="img-circle" alt="User Image">

                <p>
                  Alexander Pierce - Web Developer
                  <small>Member since Nov. 2012</small>
                </p>
              </li>
              <!-- Menu Footer-->
              <li class="user-footer">
                <div class="pull-left">
                  <a href="#" class="btn btn-default btn-flat">Profile</a>
                </div>
                <div class="pull-right">
                  <a href="<?= Url::to(['site/logout'])?>" data-method="post" class="btn btn-default btn-flat">Sign out</a>
                </div>
              </li>
               <!-- Control Sidebar Toggle Button -->
            </ul>
          </li>
        </ul>
      </div>
    </nav>
</header>
<!-- Left side column. contains the logo and sidebar -->
<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">

      <?php
      echo Menu::widget([
                  'options' => ['tag' => 'ul class="sidebar-menu" data-widget="tree"'],
                  'submenuTemplate' => "\n<ul class='treeview-menu'>\n{items}\n</ul>\n",
                  'items' => [
                      ['label' => 'MAIN NAVIGATION', 'options' => ['class' => 'header']],
                      
                      ['label' => 'Dashboard', 'url' => ['site/index'], 'template' => '<a href="{url}"><i class="fa fa-dashboard"></i> <span>{label}</span></a>'],

                      ['label' => 'Article', 'url' => 'article/index', 'options'=> ['class'=>'treeview'], 'template' => '<a href="{url}"><i class="fa fa-files-o"></i><span>{label}</span><span class="pull-right-container"><i class="fa fa-angle-left pull-right"></i></span></a>', 'items' => [
                          ['label' => 'Article List', 'url' => ['article/index'], 'template' => '<li><a href="{url}"><i class="fa fa-circle-o"></i>{label}</a></li>'],
                          ['label' => 'Approve Request', 'url' => '#', 'template' => '<li><a href="{url}"><i class="fa fa-circle-o"></i>{label}</a></li>'],
                      ]],

                      ['label' => 'Short Story', 'url' => '#', 'options'=> ['class'=>'treeview'], 'template' => '<a href="{url}"><i class="fa fa-files-o"></i><span>{label}</span><span class="pull-right-container"><i class="fa fa-angle-left pull-right"></i></span></a>', 'items' => [
                          ['label' => 'List SS', 'url' => ['ss/index'], 'template' => '<li><a href="{url}"><i class="fa fa-circle-o"></i>{label}</a></li>'],
                          ['label' => 'Approve Request', 'url' => '#', 'template' => '<li><a href="{url}"><i class="fa fa-circle-o"></i>{label}</a></li>'],
                      ]],

                      ['label' => 'Topics', 'url' => '#', 'options'=> ['class'=>'treeview'], 'template' => '<a href="{url}"><i class="fa fa-files-o"></i><span>{label}</span><span class="pull-right-container"><i class="fa fa-angle-left pull-right"></i></span></a>', 'items' => [
                          ['label' => 'Topic List', 'url' => ['topic/index'], 'template' => '<li><a href="{url}"><i class="fa fa-circle-o"></i>{label}</a></li>'],
                          ['label' => 'Super Topics', 'url' => ['super-topic/index'], 'template' => '<li><a href="{url}"><i class="fa fa-circle-o"></i>{label}</a></li>'],
                          ['label' => 'Default Home and Nav. Topics', 'url' => '#', 'template' => '<li><a href="{url}"><i class="fa fa-circle-o"></i>{label}</a></li>'],
                      ]],

                      ['label' => 'User', 'url' => '#', 'options'=> ['class'=>'treeview'], 'template' => '<a href="{url}"><i class="fa fa-files-o"></i><span>{label}</span><span class="pull-right-container"><i class="fa fa-angle-left pull-right"></i></span></a>', 'items' => [
                          ['label' => 'Manage User', 'url' => ['panel/index'], 'template' => '<li><a href="{url}"><i class="fa fa-circle-o"></i>{label}</a></li>'],
                      ]],
                  ],
              ]);


      ?>
    </section>
    <!-- /.sidebar -->
</aside>


<div class="content-wrapper">

    <section class="content-header">
      <h1>
        List of Articles
        <small>Manage Articles</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="#">Tables</a></li>
        <li class="active">Data tables</li>
      </ol>
    </section>

    <section class="content">
        <?= Alert::widget() ?>
        <?= $content ?>
    </section>
</div>
</div>
<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>